adds Offboarding Docs
moondance-labs/tanssi-docs pull request #118
Opened 2024-03-09 00:08 UTC by themacexpert

### Description

Adds Docs for Offboarding as a block producer. 

### Checklist

- [x] I have added a label to this PR 🏷️
- [x] I have run my changes through Grammarly
- [x] If this page requires a disclaimer, I have added one
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects

2024-03-12 22:03 UTC, eshaben requested changes
thanks for putting this together!! 🙌

2024-03-12 22:03 UTC, eshaben commented on node-operators/block-producers/offboarding/offboarding.md
> +
Just as a heads up, I recently got some feedback on the account setup page that I need to clarify a bit about the sessions and the delay so I have to do that yet - so if you use it as a reference, just try to make it a bit more clear 🙂

2024-03-19 00:59 UTC, themacexpert commented on node-operators/block-producers/offboarding/offboarding.md
> +The unmapping step is taken only as part of the offboarding process. If you need to rotate / change your session keys, for example, a service provider runs a Tanssi block producer on your behalf and
I changed this section up a bit but hadn't pushed the commit prior to the review

2024-03-19 01:03 UTC, themacexpert commented on node-operators/block-producers/offboarding/offboarding.md
> +7. For **at**, enter the session key at which you submitted the delegate request
Yes, done!

2024-03-19 18:33 UTC, themacexpert commented on node-operators/block-producers/offboarding/offboarding.md
> +6. Select **Stake** from the dropdown
Done!

2024-03-20 04:06 UTC, eshaben commented on node-operators/block-producers/offboarding/.pages
> +  - 'Decommission Block Producer': 'account.md'
```suggestion
  - 'Decommission Your Account': 'account.md'
```

I wanted to put "Decommission Your Block Producer," so it sort of aligns with the rest of the titles, but thats too long -- it gets broken into two lines. So I'd prefer "Decommission Your Account" for the left nav

2024-03-20 04:06 UTC, eshaben commented on node-operators/block-producers/offboarding/account.md
> +5. In the **option** field, you can select **CandidateTotalStake** to see the amount you have staked in Plank. Alternatively, you can select **AutoCompoundingShares** or **ManualRewardShares** depend
i misled you on this; i'm sorry! 😅 😬  - its not `CandidateTotalStake`. I'm making sure I 100% understand this before getting back to you

2024-03-21 04:30 UTC, eshaben commented on node-operators/block-producers/offboarding/account.md
> +5. In the **option** field, you can select **CandidateTotalStake** to see the amount you have staked in Plank. Alternatively, you can select **AutoCompoundingShares** or **ManualRewardShares** depend
gahhh, so there isn't a super straightforward way to do this with polkadot.js apps right now. users can query each of the following and add them: ManualRewardShares + AutoCompoundingShares + JoiningShares

so maybe for this guide, for step 5 use JoiiningShares and then after the image just tell them to repeat the steps and query ManualRewardShares and AutoCompoundingShares and add em up to get their self-del?

2024-03-21 04:32 UTC, eshaben commented on node-operators/block-producers/offboarding/account.md
> +5. In the **option** field, you can select **CandidateTotalStake** to see the amount you have staked in Plank. Alternatively, you can select **AutoCompoundingShares** or **ManualRewardShares** depend
CandidateTotalStake includes their entire stake for all their delegations (not just their own) - shocking, i know! 🙃  haha i don't know how i made that mistake initially, my bad

2024-03-21 04:33 UTC, eshaben commented on node-operators/block-producers/offboarding/account.md
> +6. Select **Stake** from the dropdown
i'd say switch this to shares

2024-03-21 04:34 UTC, eshaben commented on node-operators/block-producers/offboarding/account.md
> +7. Enter the amount to unstake. You'll need to submit the value in [Planck](https://wiki.polkadot.network/docs/learn-DOT#the-planck-unit){target=\_blank}. As a reminder, the minimum stake amount is {
we should switch this to shares

2024-03-25 17:47 UTC, themacexpert commented
Thanks for the review @eshaben, fixed!

2024-03-25 21:10 UTC, eshaben approved these changes
Nice! LGTM! 🚢

2024-03-25 21:31 UTC, merged