Builders>appchain devs/dapp devs reorg
moondance-labs/tanssi-docs pull request #120
Opened 2024-03-11 15:37 UTC by eshaben

### Description

Reorganize the Builders section so that it contains content specific to building an Appchain, and move all content specific to what developers can build on top of an Appchain to a new section, the Explore section.

This PR also merges the Substrate and EVM Subsquid page into one "Quick Start" page under Explore > Integrations > Indexers > Subsquid

Redirects PR: https://github.com/papermoonio/tanssi-mkdocs/pull/30

### Checklist

- [x] I have added a label to this PR 🏷️
- [x] I have run my changes through Grammarly
- [x] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects

2024-03-13 21:41 UTC, augustocollado requested changes
It looks great!
I feel that there must be a better name than "Explore" for the section, but I couldn't come up with a better one :P
(Oh, and there's some conflicts to fix)

2024-03-13 21:41 UTC, augustocollado commented on explore/developer-toolkit/index.md
> +description: TODO
```suggestion
description: Learn to interact with your Tanssi appchain using tools like Chopsticks, Polkadot.js, Sidecar API, and Remix, Hardhat, Foundry (if Ethereum compatible).
```

2024-03-13 21:41 UTC, augustocollado commented on explore/integrations/index.md
> +description: TODO
```suggestion
description: Learn about the integrations that allow you to index and query Ethereum data on Your Tanssi EVM Appchain and the Oracles to provide asset price feeds.
```

2024-03-14 11:36 UTC, albertov19 requested changes
I agree with @augustocollado that maybe "Explore" is not the best name for it. But I'm also unsure what is the right name.

"Appchain API" is the right way to express it to me, but maybe a different word would be better.

I want to put this section next to "Builders," tho because it is not like:

"Section on Appchains" | "Section for Infra" | "Philosophical Section" | "Section around Appchains"

2024-03-21 20:38 UTC, augustocollado submitted a review, later dismissed
Looks great!

2024-03-22 13:29 UTC, albertov19 submitted a review, later dismissed
LGTM

2024-03-29 18:10 UTC, themacexpert approved these changes
LGTM  👍

2024-03-29 18:15 UTC, merged