Naming convention changes
moondance-labs/tanssi-docs pull request #121
Opened 2024-03-11 19:41 UTC by augustocollado

### Description

This PR applies the new naming convention to every article and diagram.
It changes:
ConatainerChain & Apppchain -> appchains (only capitalized when in titles or beginning the sentence)
Collators -> block producers

### Checklist

- [ ] I have added a label to this PR 🏷️
- [ ] I have run my changes through Grammarly
- [ ] If this page requires a disclaimer, I have added one
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects

2024-03-12 22:47 UTC, eshaben requested changes
I did a search for 'Appchain' with a capitalized A in visual studio code, and came across some files that still need to be updated - mostly in comments in code snippets, but also a few text snippets, a few meta-descriptions, the README.md, and scattered throughout some of the newer files (maybe just missed do to merging at different times - not sure)

Also did a search for "Collators" - the node-operators/index.md file needs to be updated (title and description), the alt text for image 3 in learn/tanssi/technical-features.md needs to be updated

There are also a few snippets that use "evm_containerchain" as a variable, this can be changed to "evm_appchain"

"ContainerChain" when searched also came back with a few hits - mostly on index.md pages, on the CONTRIBUTING.md page, and also one time in a comment on a snippet (feeder.ts)

While we are applying these conventions, are there specifications outlined for "Dedicated appchains" and "Snap appchains" should dedicated and snap be capitalized?

2024-03-12 22:47 UTC, eshaben commented on builders/build/customize/prerequisites.md
> +title: Prerequisites for building an appchain
```suggestion
title: Prerequisites for Building an Appchain
```

2024-03-12 22:47 UTC, eshaben commented on builders/build/templates/evm.md
> +Tanssi EVM appchain template is built on top of the [Substrate Appchain template](/builders/build/templates/substrate/){target=\_blank}. Consequently, it includes the same [baseline modules](/builder
```suggestion
The Tanssi EVM appchain template is built on top of the [Substrate Appchain template](/builders/build/templates/substrate/){target=\_blank}. Consequently, it includes the same [baseline modules](/builders/build/templates/substrate/#included-modules).
```

2024-03-12 22:47 UTC, eshaben commented on builders/build/templates/overview.md
> +- **[XCM](https://wiki.polkadot.network/docs/learn-xcm){target=\_blank}** - handles the ingestion and dispatch of incoming downward and lateral messages, allowing a Tanssi  appchain to communicate an
```suggestion
- **[XCM](https://wiki.polkadot.network/docs/learn-xcm){target=\_blank}** - handles the ingestion and dispatch of incoming downward and lateral messages, allowing a Tanssi appchain to communicate and interoperate with the other sibling chains within the ecosystem
```

2024-03-12 22:47 UTC, eshaben commented on builders/tanssi-network/networks/dancebox/demo-evm-containerchain.md
> +      EvmAppchain: {
This should actually be `evmAppchain`

2024-03-12 22:47 UTC, eshaben commented on builders/tooling/oracles/acurast.md
> +5. Paste in the code of your job script. You can copy and paste directly from the [script of the sample BTC/USD price feed](https://github.com/Acurast/acurast-evm-oracle-sample/blob/main/acurast_scri
```suggestion
5. Paste in the code of your job script. You can copy and paste directly from the [script of the sample BTC/USD price feed](https://github.com/Acurast/acurast-evm-oracle-sample/blob/main/acurast_scripts/oracle_job.js){target=\_blank}, just make sure to change the destination contract to one that you deployed on your appchain and the RPC node to your appchain's RPC URL, which can be found on the [Tanssi dApp](https://apps.tanssi.network/){target=\_blank}
```

2024-03-12 22:47 UTC, eshaben commented on learn/tanssi/overview.md
> +![Data Preservers  of an appchain & Tanssi](/images/learn/tanssi/overview/light-overview-2.webp#only-light)
```suggestion
![Data Preservers of an appchain & Tanssi](/images/learn/tanssi/overview/light-overview-2.webp#only-light)
```

2024-03-14 03:33 UTC, augustocollado commented
There are no definitions yet for dedicated or snaps
There were still lots of remaining references to deprecated terms, thanks :)

> I did a search for 'Appchain' with a capitalized A in visual studio code, and came across some files that still need to be updated - mostly in comments in code snippets, but also a few text snippets, a few meta-descriptions, the README.md, and scattered throughout some of the newer files (maybe just missed do to merging at different times - not sure)
> 
> Also did a search for "Collators" - the node-operators/index.md file needs to be updated (title and description), the alt text for image 3 in learn/tanssi/technical-features.md needs to be updated
> 
> There are also a few snippets that use "evm_containerchain" as a variable, this can be changed to "evm_appchain"
> 
> "ContainerChain" when searched also came back with a few hits - mostly on index.md pages, on the CONTRIBUTING.md page, and also one time in a comment on a snippet (feeder.ts)
> 
> While we are applying these conventions, are there specifications outlined for "Dedicated appchains" and "Snap appchains" should dedicated and snap be capitalized?

2024-03-15 20:30 UTC, eshaben reviewed
Sweeeet! One last fix

2024-03-15 20:30 UTC, eshaben commented on builders/interact/ethereum-api/indexers/subsquid.md
>  title: Index Your Tanssi EVM AppChain with Subsquid
```suggestion
title: Index Your Tanssi EVM Appchain with Subsquid
```

2024-03-18 22:46 UTC, merged