Generalization on learn/framework/modules/
moondance-labs/tanssi-docs pull request #195
Opened 2024-11-07 11:50 UTC by augustocollado

### Description

This PR generalizes modules sections:
It renames pallets to modules, and also removes some irrelevenat info about system and parachains pallets.

### Checklist

- [ ] I have added a label to this PR 🏷️
- [ ] I have run my changes through Grammarly
- [ ] If this page requires a disclaimer, I have added one
- [ ] If pages have been moved around, I have created an additional PR in `tanssi-mkdocs` to update redirects

2024-11-07 17:45 UTC, albertov19 requested changes
Some more tiny nitpicks

2024-11-07 17:45 UTC, albertov19 commented on learn/framework/modules.md
> +To build the Runtime, Substrate provides many built-in modules (AKA pallets) that can be freely used as building blocks to compose and interact with any other custom-made modules, allowing teams to c
```suggestion
To build the Runtime, Substrate provides many built-in modules (also known as pallets) that can be freely used as building blocks to compose and interact with any other custom-made modules, allowing teams to create unique behaviors according to the specific requirements of their Tanssi appchain.
```

2024-11-07 17:45 UTC, albertov19 commented on learn/framework/modules.md
> +- **[pallet_balances](https://paritytech.github.io/substrate/master/pallet_balances/index.html){target=\_blank}** - the Balances modules provides functions for handling accounts and balances for the
```suggestion
- **[Balances module](https://paritytech.github.io/substrate/master/pallet_balances/index.html){target=\_blank}** - it provides functions for handling accounts and balances for the Tanssi appchain native currency
```

2024-11-07 17:45 UTC, albertov19 commented on learn/framework/modules.md
> +- **[pallet_balances](https://paritytech.github.io/substrate/master/pallet_balances/index.html){target=\_blank}** - the Balances modules provides functions for handling accounts and balances for the
I suggest we do the others this way :)

2024-11-08 13:47 UTC, albertov19 requested changes
Some notes

2024-11-08 14:44 UTC, augustocollado commented on learn/framework/modules.md
> +- **[Balances module](https://paritytech.github.io/substrate/master/pallet_balances/index.html){target=\_blank}** - it provides functions for handling accounts and balances for the Tanssi appchain na
Ah shoot! yes, will do

2024-11-08 14:47 UTC, augustocollado commented on learn/framework/modules.md
> +- **[Balances module](https://paritytech.github.io/substrate/master/pallet_balances/index.html){target=\_blank}** - it provides functions for handling accounts and balances for the Tanssi appchain na
Wait. that was in this same PR, and it's already done -> https://github.com/moondance-labs/tanssi-docs/pull/195/commits/414c23300fe5c3bddf8b7a031908e97eb8b4308c

2024-11-08 20:58 UTC, albertov19 commented on learn/framework/modules.md
> +- **[Balances module](https://paritytech.github.io/substrate/master/pallet_balances/index.html){target=\_blank}** - it provides functions for handling accounts and balances for the Tanssi appchain na
Nah but I mean the actual word module that is repeated multiple times in each bullet point

2024-11-19 15:25 UTC, albertov19 approved these changes
LGTM!

2024-11-19 15:30 UTC, merged