builder - templates - overview
moondance-labs/tanssi-docs pull request #196
Opened 2024-11-07 15:53 UTC by augustocollado

### Description

This PR generalizes the article uilders/build/templates/overview/, removing polkadot as the only security provider

### Checklist

- [ ] I have added a label to this PR 🏷️
- [ ] I have run my changes through Grammarly
- [ ] If this page requires a disclaimer, I have added one
- [ ] If pages have been moved around, I have created an additional PR in `tanssi-mkdocs` to update redirects

2024-11-07 16:41 UTC, albertov19 requested changes
Love how things are panning out. Left some minor comments. Unsure if we will use still word pallets, maybe we just rename that as Module and not call it the official way

2024-11-07 16:41 UTC, albertov19 commented on builders/build/templates/overview.md
> +description: Tanssi includes templates to kick-start the development of an appchain offering options such as a basic one and another featuring full EVM (Ethereum) support.
```suggestion
description: Tanssi includes templates to kick-start the development of an appchain with full EVM (Ethereum) support and minimal engineering overhead.
```

2024-11-07 16:41 UTC, albertov19 commented on builders/build/templates/overview.md
> +description: Tanssi includes templates to kick-start the development of an appchain offering options such as a basic one and another featuring full EVM (Ethereum) support.
I think it was discussed that we just mention the EVM template btw (considering the previous PRs we merged)

2024-11-07 16:41 UTC, albertov19 commented on builders/build/templates/overview.md
> +Appchains deployed through Tanssi are fully customizable blockchains benefiting from a shared set of sequencers and the security of a provider of their choice ([Symbiotic](https://symbiotic.fi/){targ
```suggestion
Appchains deployed through Tanssi are fully customizable blockchains benefiting from a shared set of sequencers and the security of a provider of their choice (for example, [Symbiotic](https://symbiotic.fi/){target=\_blank} for Ethereum). They also need to implement the necessary functionalities and configurations to support the Tanssi protocol, which the templates presented in this article already do, making it easier for developers.
```

2024-11-07 16:41 UTC, albertov19 commented on builders/build/templates/overview.md
> +- **[Baseline Tanssi appchain template](/learn/tanssi/included-templates/#baseline-appchain-template){target=\_blank}** - a template that provides the basic platform to start adding custom logic
Maybe we remove? Unsure

2024-11-07 16:41 UTC, albertov19 commented on builders/build/templates/overview.md
>  - **[pallet_balances](https://paritytech.github.io/substrate/master/pallet_balances/index.html){target=\_blank}** - the Balances pallet provides functions for handling accounts and balances for the T
Call them pallets still?

2024-11-07 16:59 UTC, augustocollado commented on builders/build/templates/overview.md
>  - **[pallet_balances](https://paritytech.github.io/substrate/master/pallet_balances/index.html){target=\_blank}** - the Balances pallet provides functions for handling accounts and balances for the T
Nope, I missed those!

2024-11-08 10:37 UTC, albertov19 approved these changes
LGTM

2024-11-08 13:54 UTC, merged