Adds Hardhat Docs
moondance-labs/tanssi-docs pull request #45
Opened 2023-10-13 23:55 UTC by themacexpert

### Description

Adds Hardhat Docs and images. Built this off the same branch as the Remix page because they are both living in the same section (and I wanted to fend off merge conflicts) 

### Checklist

- [x] If this page requires a disclaimer, I have added one
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects

2023-10-17 03:51 UTC, eshaben commented
Just changed the base branch so it doesn't have all the Remix changes in this PR and is easier to review!

2023-10-17 04:09 UTC, eshaben requested changes
Looks good! The screenshots are like perfectly sized ✨ 

Mostly little grammar things. I also have the same comments here as I did on the Remix PR about the icons, if you could please fix them! 🙂

2023-10-17 04:09 UTC, eshaben commented on builders/interact/ethereum-api/dev-env/hardhat.md
> +```js
please run prettier on this snippet, looks like it's using 4 spaces instead of 2

2023-10-17 04:09 UTC, eshaben commented on builders/interact/ethereum-api/dev-env/hardhat.md
> +};
can you please run prettier here? i think there are some trailing commas missing 🤔

2023-10-17 04:09 UTC, eshaben commented on builders/interact/ethereum-api/dev-env/hardhat.md
> +If you're deploying to another CointainerChain, make sure that you specify the correct network. The network name needs to match how it's defined in the `hardhat.config.js`.
```suggestion
If you're deploying to another CointainerChain, make sure that you specify the correct network. The network name needs to match how it's defined in `hardhat.config.js`.
```

2023-10-17 04:09 UTC, eshaben commented on builders/interact/ethereum-api/dev-env/hardhat.md
> +Next you can take the following steps, entering in one line at a time:
```suggestion
Next, you can take the following steps, entering one line at a time:
```

2023-10-17 04:09 UTC, eshaben commented on builders/interact/ethereum-api/dev-env/hardhat.md
> +You should see `5` or the value you have stored initially.
```suggestion
You should see `5` or the value you initially stored.
```

2023-10-17 04:09 UTC, eshaben commented on builders/interact/ethereum-api/dev-env/hardhat.md
> +# Using Hardhat to Deploy to your EVM ContainerChain
```suggestion
# Using Hardhat to Deploy to Your EVM ContainerChain
```

2023-10-17 04:09 UTC, eshaben commented on builders/interact/ethereum-api/dev-env/hardhat.md
> +## Hardhat Configuration File {: #hardhat-configuration-file }
```suggestion
## The Hardhat Configuration File {: #hardhat-configuration-file }
```

to match The Contract File 🤷‍♀️

2023-10-19 06:42 UTC, eshaben requested changes
Noticed some things I missed last time or possibly when you ran prettier it changed some of the formatting in ways it shouldn't have

2023-10-19 06:42 UTC, eshaben commented on builders/interact/ethereum-api/dev-env/hardhat.md
> +   ```
these are all showing up as 1s

2023-10-19 06:42 UTC, eshaben commented on builders/interact/ethereum-api/dev-env/hardhat.md
> +   !!! note
this isn't rendered correctly

2023-10-19 06:42 UTC, eshaben commented on builders/interact/ethereum-api/dev-env/hardhat.md
> +5. A menu will appear which will allow you to create a new project or use a sample project. For this example, you can choose **Create an empty hardhat.config.js**
also showing up as a 1

2023-10-19 06:42 UTC, eshaben commented on builders/interact/ethereum-api/dev-env/hardhat.md
> +Before you can deploy the contract to your ContainerChain, you'll need to modify the Hardhat configuration file and create a secure file to store your private key in.
add note about never storing private keys in a javascript file

2023-10-19 06:42 UTC, eshaben commented on builders/interact/ethereum-api/dev-env/hardhat.md
> +If you're deploying to another CointainerChain, make sure that you specify the correct network. The network name needs to match how it's defined in `hardhat.config.js`.
```suggestion
If you're deploying to another ContainerChain, make sure that you specify the correct network. The network name needs to match how it's defined in `hardhat.config.js`.
```

2023-10-19 06:42 UTC, eshaben commented on builders/interact/ethereum-api/dev-env/hardhat.md
> +   ```
these are all showing up as 1s

2023-10-19 15:25 UTC, themacexpert commented
important fixes, thanks for catching @eshaben

2023-10-19 18:44 UTC, eshaben approved these changes
Nice job. LGTM ✨

2023-10-19 18:44 UTC, merged