Add Talisman Eth API and Substrate API Wallet Pages
moondance-labs/tanssi-docs pull request #47
Opened 2023-10-17 07:50 UTC by themacexpert

### Description

Adds Talisman Pages for Eth API and Substrate API (different pages for each)

### Checklist

- [x] If this page requires a disclaimer, I have added one
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects

2023-10-17 21:06 UTC, eshaben requested changes
Nice job!

The talisman light mode icons aren't appearing because they have `-light.png` at the end of the file name. So just need to remove that so they're both `talisman.png`.

Also, it doesn't look like they are the same size 256x256 as the wallets icon, can you please double check and fix as needed? Colors look like they are on point 👌

The setting up section (after splitting out the creating an account bit to a new section) can be a text snippet shared between the ethereum and substrate pages!

2023-10-17 21:06 UTC, eshaben commented on builders/interact/ethereum-api/wallets/talisman.md
> +This guide focused specifically on configuring Talisman to work with your EVM ContainerChain, but Talisman is also a full featured wallet for Substrate (Polkadot) accounts. Under the Substrate API se
```suggestion
This guide focused specifically on configuring Talisman to work with your EVM ContainerChain, but Talisman is also a full-featured wallet for Substrate (Polkadot) accounts. Under the Substrate API section, you'll find a similar tutorial for configuring Talisman to work with Substrate-based chains.
```

2023-10-17 21:06 UTC, eshaben commented on builders/interact/ethereum-api/wallets/talisman.md
> +To create your first Ethereum account, take the following steps:
This should be its own section "Creating an Ethereum Account" and then the importing section can be after this one

2023-10-18 01:49 UTC, themacexpert commented
Thanks for the review @eshaben

2023-10-19 06:48 UTC, eshaben approved these changes
Looks good to me! I'll approve now, but I think after committing the one capitalization fix, I'll need to approve again haha... if that's the case, just tag me or request my review again please! 🙂

2023-10-19 06:48 UTC, eshaben commented on builders/interact/substrate-api/wallets/talisman.md
> +Talisman already comes pre-configured with support for the Tanssi Dancebox Testnet. You just need to first ensure that you have enabled support for TestNets on Talisman. Remember that the Tanssi Danc
```suggestion
Talisman already comes pre-configured with support for the Tanssi Dancebox Testnet. You just need to first ensure that you have enabled support for TestNets on Talisman. Remember that the Tanssi Dancebox TestNet itself is not a ContainerChain; it is the Substrate-based parachain that orchestrates and manages the launch of Tanssi ContainerChains. To configure your Talisman to work with Dancebox, take the following steps: 
```

2023-10-19 18:46 UTC, eshaben approved these changes

2023-10-19 18:47 UTC, merged