Add Subsquid Indexer Pages under Ethereum and Substrate API
moondance-labs/tanssi-docs pull request #59
Opened 2023-12-01 17:28 UTC by themacexpert

### Description

These are quick start pages under the Ethereum-API and Substrate-API pages to get users quickly up to speed on indexing data on their ContainerChain. For a more comprehensive tutorial, users should see the Subsquid tutorial under the tutorials section. 

### Checklist

- [x] If this page requires a disclaimer, I have added one
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects

2023-12-05 19:44 UTC, eshaben requested changes
Left some comments on some minor things. Mostly left comments on the EVM guide, but they all will need to be applied to the Substrate guide too, please!

A couple of things to watch for: there should be no periods at the end of list items and "Your" in titles should be capitalized

I think we need a different icon for the Indexers icon. Sorry, I'm a real stickler about these haha. I can take a look to see if I can find something. Will let you know 🙂

2023-12-05 19:44 UTC, eshaben commented on builders/interact/ethereum-api/indexers/index.md
> +description: Learn how to use Indexers to ingest, process, and query EVM data on your Tanssi EVM ContainerChain.
This description is too short. Should be a minimum of 120 characters, but no more than 160

2023-12-05 19:44 UTC, eshaben commented on builders/interact/ethereum-api/indexers/subsquid.md
> +description: Learn how to use Subsquid, a query node framework for Substrate-based chains, to index and process EVM data your Tanssi EVM ContainerChain.
```suggestion
description: Learn how to use Subsquid, a query node framework for Substrate-based chains, to index and process EVM data on your Tanssi EVM ContainerChain.
```

2023-12-05 19:44 UTC, eshaben commented on builders/interact/ethereum-api/indexers/subsquid.md
> +title: Index your Tanssi EVM ContainerChain with Subsquid
This title is four characters too long. The title should be no more than 60 characters, but you have to keep in mind that `| Tanssi Docs` is appended to the title so in this case this title really would be `Index your Tanssi EVM ContainerChain with Subsquid | Tanssi Docs`

Also `Your` should be capitalized

2023-12-05 19:44 UTC, eshaben commented on builders/interact/ethereum-api/indexers/subsquid.md
> +# Indexing your EVM ContainerChain with Subsquid
```suggestion
# Indexing Your EVM ContainerChain with Subsquid
```

2023-12-05 19:44 UTC, eshaben commented on builders/interact/ethereum-api/indexers/subsquid.md
> +## Index EVM Data on your ContainerChain {: #index-evm-data-on-your-containerchain}
```suggestion
## Index EVM Data on Your ContainerChain {: #index-evm-data-on-your-containerchain}
```

2023-12-05 19:44 UTC, eshaben commented on builders/interact/ethereum-api/indexers/subsquid.md
> +
```suggestion
```

2023-12-05 19:44 UTC, eshaben commented on builders/interact/ethereum-api/indexers/subsquid.md
> +  - [Squid CLI](https://docs.subsquid.io/squid-cli/installation/){target=_blank}
```suggestion
 - [Node.js](https://nodejs.org/en/download/){target=_blank} version 16 or newer
 - [Docker](https://docs.docker.com/get-docker/){target=_blank}
 - [Squid CLI](https://docs.subsquid.io/squid-cli/installation/){target=_blank}
```

2023-12-05 19:44 UTC, eshaben commented on builders/interact/ethereum-api/indexers/subsquid.md
> +3. Modify the `src/processor.ts` file to set the data source to the RPC URL of your ContainerChain. Remove the `archive: lookupArchive('eth-mainnet')` line as a Squid archive will not be used. Here,
```suggestion
3. Modify the `src/processor.ts` file to set the data source to the RPC URL of your ContainerChain. Remove the `archive: lookupArchive('eth-mainnet')` line as a Squid archive will not be used. Here, the RPC URL of the demo EVM ContainerChain is specified. The Squid project will use the RPC endpoint to ingest the relevant data
```

2023-12-05 19:44 UTC, eshaben commented on builders/interact/ethereum-api/indexers/subsquid.md
> +4. Launch Postgres and detach by running:
```suggestion
4. Launch Postgres by running:
```

2023-12-05 19:44 UTC, eshaben commented on builders/interact/ethereum-api/indexers/subsquid.md
> +7. You can now run queries, such as the sample query below, against your Squid on the GraphQL playground at [http://localhost:4350/graphql](http://localhost:4350/graphql){target=_blank}. If you've mo
```suggestion
7. You can now run queries, such as the sample query below, against your Squid on the GraphQL playground at [http://localhost:4350/graphql](http://localhost:4350/graphql){target=_blank}. If you've modified the template EVM squid to index different data, you'll need to modify this query accordingly
```

2023-12-05 19:44 UTC, eshaben commented on builders/interact/ethereum-api/indexers/subsquid.md
> +And that's all you have to do to configure your Subsquid project to index EVM data on your Tanssi EVM ContainerChain! Now you can update the `schema.graphql`, `main.ts`, and `src/processor.ts` files
```suggestion
And that's all you have to do to configure your Subsquid project to index EVM data on your Tanssi EVM ContainerChain! Now you can update the `schema.graphql`, `src/main.ts`, and `src/processor.ts` files to index the data you need for your project!
```

2023-12-05 19:44 UTC, eshaben commented on builders/interact/ethereum-api/indexers/subsquid.md
> +If you're interested in a more comprehensive step-by-step tutorial to get started indexing data your ContainerChain, you can check out the [Using Subsquid to Index Your ContainerChain](/builders/tuto
```suggestion
If you're interested in a more comprehensive step-by-step tutorial to get started indexing data for your ContainerChain, you can check out the [Using Subsquid to Index Your ContainerChain](/builders/tutorials/subsquid/){target=_blank} tutorial!
```

2023-12-05 19:44 UTC, eshaben commented on builders/interact/substrate-api/indexers/index.md
> +description: Learn how to use Indexers to ingest, process, and query Substrate data on your Tanssi Substrate ContainerChain.
This one is also a tad bit too short

2023-12-05 19:44 UTC, eshaben commented on builders/interact/substrate-api/indexers/index.md
> +title: Indexers
Ideally, this should be different than the other title on the EVM side of things

2023-12-05 19:44 UTC, eshaben commented on builders/interact/substrate-api/indexers/subsquid.md
> +title: Index your Tanssi Substrate ContainerChain with Subsquid
This is also too long

2023-12-05 19:44 UTC, eshaben commented on builders/interact/substrate-api/indexers/subsquid.md
> +      }
```suggestion
    query MyQuery {
      accountsConnection(orderBy: id_ASC) {
        totalCount
      }
    }
```

2023-12-06 00:15 UTC, eshaben reviewed
Looks like the substrate-api index page icons still need to be changed, please! Missed a couple minor things earlier. Aside from these little things, it looks good!

2023-12-06 00:15 UTC, eshaben commented on builders/interact/substrate-api/indexers/subsquid.md
> +And that's all you have to do to configure your Subsquid project to index Substrate data on your Tanssi Substrate ContainerChain! Now you can update the `schema.graphql`, `src/main.ts`, `typgen.json`
```suggestion
And that's all you have to do to configure your Subsquid project to index Substrate data on your Tanssi Substrate ContainerChain! Now you can update the `schema.graphql`, `src/main.ts`, `typegen.json`, and `src/processor.ts` files to index the data you need for your project!
```

2023-12-06 00:15 UTC, eshaben commented on builders/interact/substrate-api/indexers/subsquid.md
> +7. You can query your template Substrate squid with the below sample query. If you've modified the template Substrate squid to index different data, you'll need to modify this query accordingly
```suggestion
7. You can query your template Substrate Squid with the below sample query. If you've modified the template Substrate squid to index different data, you'll need to modify this query accordingly
```

2023-12-06 00:29 UTC, themacexpert commented
Thank you @eshaben! fixed

2023-12-06 00:31 UTC, eshaben approved these changes
LGTM!

2023-12-06 00:31 UTC, merged