Add Viem Docs
moondance-labs/tanssi-docs pull request #68
Opened 2023-12-15 02:44 UTC by themacexpert

### Description

Add Viem Docs

### Checklist

- [x] I have added a label to this PR 🏷️
- [x] If this page requires a disclaimer, I have added one
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects

2023-12-18 16:20 UTC, eshaben requested changes
nice job! the index page icons look a bit pixelated/blurry and they don't look like the right size. are you using an svg or png?

2023-12-18 16:20 UTC, eshaben commented on builders/interact/ethereum-api/libraries/viem.md
> +If the transaction was successful, in your terminal you'll see the transaction hash has been printed out. You can also use the `balances.ts` script to check that the balances for the origin and recei
```suggestion
If the transaction was successful, in your terminal, you'll see the transaction hash has been printed out. You can also use the `balances.ts` script to check that the balances for the origin and receiving accounts have changed. The entire workflow would look like this:
```

2023-12-18 16:20 UTC, eshaben commented on builders/interact/ethereum-api/libraries/viem.md
> +--8<-- 'text/libraries/contract.md'
This snippet has a grammar issue: "Next you can add the Solidity code to the file:" should be "Next, you..."

2023-12-18 16:20 UTC, eshaben commented on .snippets/code/ethereum-api/viem/.prettierrc.js
> +// prettierrc.cjs or .prettierrc.js
This doesn't look like this file is used anywhere, and we typically don't tell users how to configure prettier in any of our demos anyways, so I think this file can probably be deleted

2023-12-18 16:20 UTC, eshaben commented on .snippets/code/ethereum-api/viem/balances.ts
> +// 1. Imports the necessary components from viem
This should just be "Import" not "Imports", please check all the snippets

2023-12-18 16:20 UTC, eshaben commented on .snippets/code/ethereum-api/viem/deploy.ts
> +  // 8. Get the transaction receipt for the deployment
Step 8 spells out "transaction" and step 7 doesn't. Let's just use "transaction". Please check all snippets

2023-12-18 16:20 UTC, eshaben commented on .snippets/code/ethereum-api/viem/read-chain-data.ts
> +// 1. Import the necessary components from viem.
```suggestion
// 1. Import the necessary components from viem
```

2023-12-18 16:20 UTC, eshaben commented on builders/interact/ethereum-api/libraries/viem.md
> +    ```
Ah ok, I see where maybe this went a little off the tracks. If you're trying to pull in the creating the client part, you can reference the Ethers tutorial where we use `// {...}` this type of comment to indicate pulling in the other parts and then use the expandable snippet to tie it altogether

2023-12-18 16:20 UTC, eshaben commented on builders/interact/ethereum-api/libraries/viem.md
> +    ```
either way, we should be displaying a visible code snippet for the users at the end of the steps

2023-12-23 23:13 UTC, themacexpert commented
I made all snippets expanded by default so it looks longer but it corresponds nicely to the #1-9 steps described in the tutorial. If it seems too big we can re-visit another approach.

2023-12-27 05:32 UTC, eshaben reviewed
I think the expandables look great! 🙌 

The viem icons need to fill the width or height (whichever is greater) of the 256 x 256px background. It looks like the logo is also a png because its a bit pixelated, but I could be wrong! I can find an svg if you need one! 🙂

2023-12-27 05:32 UTC, eshaben commented on builders/interact/ethereum-api/libraries/viem.md
> +4. Create the `client` using the `createWalletClient` function and pass in the account, network, and the HTTP RPC endpoint
There are 4 steps here, but only 3 listed in the snippet

2023-12-27 22:54 UTC, themacexpert commented
Thanks @eshaben, fixed!

2024-01-04 01:32 UTC, eshaben approved these changes
LGTM! 🚢 ✨

2024-01-04 01:32 UTC, merged