Adding third party module - example
moondance-labs/tanssi-docs pull request #73
Opened 2024-01-10 00:55 UTC by augustocollado

### Description

This PR completes the third-party module article by illustrating the process of adding a third-party pallet, the error you'll get when trying to compile, and how to apply the solution by patching the deps with dinner.
This section relies on this other repo containing the pallet: https://github.com/papermoonio/pallet-toggle

### Checklist

- [ ] I have added a label to this PR 🏷️
- [ ] If this page requires a disclaimer, I have added one
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects

2024-01-10 15:32 UTC, albertov19 requested changes
Left some feedback to improve readability :)

2024-01-10 15:32 UTC, albertov19 commented on builders/build/customize/adding-external-module.md
> +Having declared the module in the workspace `Cargo.toml` file, the dependency can now be added to the specific template `Cargo.toml` file, which is located in the folder `container-chains/templates/s
```suggestion
Having declared the module in the workspace `Cargo.toml` file, the dependency can now be added to the specific template `Cargo.toml` file, which for this example that uses the Tanssi GitHub repo, is located in the folder `container-chains/templates/simple/runtime`.
```

2024-01-10 15:32 UTC, albertov19 commented on builders/build/customize/adding-external-module.md
> +#### Configure and Add the Module to the Runtime {: #configure-module-in-the-runtime }
```suggestion
### Configure and Add the Module to the Runtime {: #configure-module-in-the-runtime }
```

2024-01-10 15:32 UTC, albertov19 commented on builders/build/customize/adding-external-module.md
> +### Compile {: #compile }
```suggestion
### Compile Runtime {: #compile-runtime }
```

2024-01-10 15:32 UTC, albertov19 commented on builders/build/customize/adding-external-module.md
> +Add the following snippet that configures the module and add the module within the `construct_runtime!`macro.
```suggestion
Next, add the following snippet in the `lib.rs` file inside the runtime folder. This configures the module and add the module within the `construct_runtime!`macro.
```

2024-01-10 15:32 UTC, albertov19 commented on builders/build/customize/adding-external-module.md
> +Finally, executing the `diener` [command](#solving-dependencies-conflicts-diener) will add a `patch` section to your workspace `Cargo.toml` file, overriding the dependencies and unifying origins and
Add an example of how the diener command is executed for this example

2024-01-16 10:44 UTC, albertov19 requested changes
Looks great! As my last piece of feedback, I would use now `termynal` 

It will be an easy thing to adapt here. Check the reference PR -> https://github.com/moondance-labs/tanssi-docs/pull/74

2024-01-16 16:38 UTC, eshaben commented on builders/build/customize/adding-external-module.md
> +To illustrate the situation, the following steps add a demo [external module](https://github.com/papermoonio/pallet-toggle.git){target=_blank} to a custom runtime based on the [baseline Appchain temp
All of the `target=_blank`s on this page should be changed to `target=\_blank`

2024-01-16 16:38 UTC, eshaben commented on builders/build/customize/adding-external-module.md
> +This `toggle` module, built for testing and educational purposes, adds a basic logic to the runtime, allowing users to switch a state between true and false.
```suggestion
This `toggle` module, built for testing and educational purposes, adds basic logic to the runtime, allowing users to switch a state between true and false.
```

2024-01-16 16:38 UTC, eshaben commented on builders/build/customize/adding-external-module.md
> +Having declared the module in the workspace `Cargo.toml` file, the dependency can now be added to the specific template `Cargo.toml` file, which for this example that uses the Tanssi GitHub repo, is
```suggestion
Having declared the module in the workspace `Cargo.toml` file, the dependency can now be added to the specific template `Cargo.toml` file, which, for this example that uses the Tanssi GitHub repo, is located in the folder `container-chains/templates/simple/runtime`.
```

2024-01-16 16:38 UTC, eshaben commented on builders/build/customize/adding-external-module.md
> +Next, add the following snippet in the `lib.rs` file inside the runtime folder. This configures the module and add the module within the `construct_runtime!`macro.
```suggestion
Next, add the following snippet to the `lib.rs` file inside the runtime folder. This configures the module and adds the module within the `construct_runtime!` macro.
```

2024-01-16 16:38 UTC, eshaben commented on builders/build/customize/adding-external-module.md
> +### Patch depedencies {: #patch-dependencies }
```suggestion
### Patch Dependencies {: #patch-dependencies }
```

2024-01-16 18:40 UTC, albertov19 commented
@augustocollado you can remove the terminal image then :)

2024-01-16 19:05 UTC, augustocollado commented
> @augustocollado you can remove the terminal image then :)

Ouch! I deleted the image, but I don't know how that copy with that name got in that new folder I created. Fixed.

> @augustocollado don't forget the `target=\_blank` as per the changes made in this PR: #76

Sorry about that, I thought I had gotten them all :S

2024-01-16 19:12 UTC, eshaben approved these changes
LGTM!

2024-01-18 15:23 UTC, albertov19 approved these changes
LGTM

2024-01-18 15:23 UTC, merged